name: Manual Newsletter Trigger

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'health-check'
        type: choice
        options:
        - health-check
        - generate-newsletter
        - dry-run
        - show-config
      debug:
        description: 'Enable debug logging'
        required: false
        default: false
        type: boolean

jobs:
  execute-action:
    runs-on: ubuntu-latest
    environment: production
    
    permissions:
      contents: read
      issues: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Execute Health Check
      if: inputs.action == 'health-check'
      run: |
        echo "🔍 Running health check..."
        if [[ "${{ inputs.debug }}" == "true" ]]; then
          python -m src.newsletter_bot --debug health || exit 1
        else
          python -m src.newsletter_bot health || exit 1
        fi
      env:
        READWISE_API_KEY: ${{ secrets.READWISE_API_KEY }}
        GLASP_API_KEY: ${{ secrets.GLASP_API_KEY }}
        RSS_FEEDS: ${{ secrets.RSS_FEEDS }}
        BUTTONDOWN_API_KEY: ${{ secrets.BUTTONDOWN_API_KEY }}
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
    
    - name: Show Configuration
      if: inputs.action == 'show-config'
      run: |
        echo "📋 Showing configuration (without sensitive values)..."
        if [[ "${{ inputs.debug }}" == "true" ]]; then
          python -m src.newsletter_bot --debug config || exit 1
        else
          python -m src.newsletter_bot config || exit 1
        fi
      env:
        READWISE_API_KEY: ${{ secrets.READWISE_API_KEY }}
        GLASP_API_KEY: ${{ secrets.GLASP_API_KEY }}
        RSS_FEEDS: ${{ secrets.RSS_FEEDS }}
        BUTTONDOWN_API_KEY: ${{ secrets.BUTTONDOWN_API_KEY }}
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
    
    - name: Generate Newsletter (Dry Run)
      if: inputs.action == 'dry-run'
      run: |
        echo "🧪 Running newsletter generation in dry-run mode..."
        if [[ "${{ inputs.debug }}" == "true" ]]; then
          python -m src.newsletter_bot --debug generate --dry-run || exit 1
        else
          python -m src.newsletter_bot generate --dry-run || exit 1
        fi
      env:
        READWISE_API_KEY: ${{ secrets.READWISE_API_KEY }}
        GLASP_API_KEY: ${{ secrets.GLASP_API_KEY }}
        RSS_FEEDS: ${{ secrets.RSS_FEEDS }}
        BUTTONDOWN_API_KEY: ${{ secrets.BUTTONDOWN_API_KEY }}
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
    
    - name: Generate Newsletter (Production)
      if: inputs.action == 'generate-newsletter'
      run: |
        echo "📧 Running newsletter generation in PRODUCTION mode..."
        echo "⚠️  This will create and publish an actual newsletter!"
        if [[ "${{ inputs.debug }}" == "true" ]]; then
          python -m src.newsletter_bot --debug generate || exit 1
        else
          python -m src.newsletter_bot generate || exit 1
        fi
      env:
        READWISE_API_KEY: ${{ secrets.READWISE_API_KEY }}
        GLASP_API_KEY: ${{ secrets.GLASP_API_KEY }}
        RSS_FEEDS: ${{ secrets.RSS_FEEDS }}
        BUTTONDOWN_API_KEY: ${{ secrets.BUTTONDOWN_API_KEY }}
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
    
    - name: Validate Generated Newsletter
      if: inputs.action == 'generate-newsletter'
      run: |
        echo "🔍 Running newsletter quality validation..."
        echo "Fetching latest newsletter from Buttondown..."
        
        # Get the latest newsletter URL from Buttondown API with better error handling
        NEWSLETTER_RESPONSE=$(curl -s -H "Authorization: Token ${{ secrets.BUTTONDOWN_API_KEY }}" \
          "https://api.buttondown.email/v1/newsletters")
        
        echo "Raw API response: $NEWSLETTER_RESPONSE"
        
        SECONDARY_ID=$(echo "$NEWSLETTER_RESPONSE" | jq -r '.results[0].secondary_id // empty')
        
        if [ -z "$SECONDARY_ID" ] || [ "$SECONDARY_ID" = "null" ]; then
          echo "❌ No newsletter found or secondary_id is null"
          echo "This might indicate the newsletter generation didn't complete successfully"
          echo "Raw Buttondown API response:"
          echo "$NEWSLETTER_RESPONSE" | jq '.'
          exit 1
        fi
        
        LATEST_URL="https://buttondown.com/filter/archive/$SECONDARY_ID"
        echo "Latest newsletter URL: $LATEST_URL"
        
        # Run validation with better error handling
        echo "Running validation check..."
        python check_briefing.py "$LATEST_URL" --verbose || {
          echo "❌ Newsletter validation failed! Issues detected."
          echo "Please review the output above and consider regenerating the newsletter."
          exit 1
        }
        
        echo "✅ Newsletter validation passed!"
      env:
        BUTTONDOWN_API_KEY: ${{ secrets.BUTTONDOWN_API_KEY }}
    
    - name: Create status comment
      if: always()
      uses: actions/github-script@v7
      with:
        script: |
          const action = '${{ inputs.action }}';
          const success = '${{ job.status }}' === 'success';
          const debug = '${{ inputs.debug }}';
          
          let title, emoji;
          if (success) {
            title = `Manual Action Completed: ${action}`;
            emoji = '✅';
          } else {
            title = `Manual Action Failed: ${action}`;
            emoji = '❌';
          }
          
          const issueBody = `## ${emoji} ${title}
          
          **Action:** \`${action}\`
          **Status:** ${success ? 'Success' : 'Failed'}
          **Debug Mode:** ${debug}
          **Timestamp:** ${new Date().toISOString()}
          **Workflow Run:** [#${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          
          ### 🔗 Quick Links
          - [Full Workflow Logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          - [Run Another Manual Action](${{ github.server_url }}/${{ github.repository }}/actions/workflows/manual-trigger.yml)
          
          ---
          *This issue was automatically created by the Manual Trigger workflow*`;
          
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: title,
            body: issueBody,
            labels: ['newsletter', 'manual', success ? 'success' : 'bug', 'automated']
          });